### ISSUE TITLE
Unknown plugin "transform-runtime"

### ISSUE THREAD

**Issue by pols1226** [pwnz22/vue2-laravel-pagination#2]
this is what I see when I type npm run watch after adding the code import Pagination from 'vue2-laravel-pagination' 
here is the error:
https://www.screencast.com/t/9ll9RKbBf

**Comment by pwnz22** [comment]
Try to install babel-transform-runtime package:
`npm install --save-dev babel-plugin-transform-runtime`

**Comment by pols1226** [comment]
Thanks buddy.. :), Cheers..
